FROM python:2.7-stretch

# We copy just the requirements.txt first to leverage Docker cache
COPY ./requirements.txt /app/requirements.txt

WORKDIR /app

RUN pip install -r requirements.txt
RUN pip install pymysql

COPY . /app

ENV DB_USERNAME=admin
ENV DB_PASSWD=Waynewong24.

RUN python tests.py
