pipeline {
	agent any
	tools { nodejs "nodejs10.x" }
	
	stages {
		stage('Trigger') {
			steps {
				echo "trigger"
			}
		}

		stage('Build') {
			steps {
                sh 'npm config ls'
				sh '''
					cd express/notejam
					npm install
				'''
			}
		}

		stage('Test') {
			agent {
                docker { image 'docker' }
            }
			steps {
				sh 'docker -v'
				echo "test"
			}
		}
	
		stage('Push') {
			steps {
				echo "push"
			}
		}
	}
}