pipeline {
	agent any
	tools { nodejs "nodejs10.x" }
	stages {
		stage('Trigger') {
			steps {
				echo "trigger"
			}
		}

		stage('Build') {
			steps {
                sh 'npm config ls'
			}
		}

		stage('Test') {
			steps {
				echo "test"
			}
		}
	
		stage('Push') {
			steps {
				echo "push"
			}
		}
	}
}