pipeline {
	agent any
	tools { nodejs "nodejs10.x" }
	
	stages {
		stage('Trigger') {
			steps {
				echo "trigger"
			}
		}

		stage('Install') {
			steps {
                sh 'npm config ls'
				sh '''
					cd express/notejam
					npm install
				'''
			}
		}

		stage('Build') {
			when { branch 'master' }
			steps { 
				sh '''
					cd express/notejam
					ls -l
					sudo docker build -t waynewong/express:${BUILD_NUMBER} .
				'''
			}
		}
	}
}